apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: thanos-object-storage
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    thanos-object-storage.yaml: {{ .Values.thanos.s3Secret }}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: thanos-object-storage
      namespace: {{ .Values.namespace }}
    type: Opaque
