apiVersion: v1
kind: Service
metadata:
  name: my-python
  namespace: default
  labels:
    k8s-app: my-python
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
  selector:
    k8s-app: my-python
