apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    team: ops
  name: ops-001
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      releaseName: ops-001-origin
      valueFiles:
      - values.ops-001.yaml
    path: charts/argo-apps
    repoURL: git@github.com:k7gh/swish.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
